from __future__ import annotations

import csv
import os
import platform
import subprocess
from pathlib import Path
from typing import Any

from src.utils.io import append_jsonl, ensure_dir, write_json
from src.utils.time import now_iso


class RunLogger:
    """Creates and manages the per-run experiment directory.

    Directory layout::

        experiments/runs/{run_id}/
            config.yaml
            environment.txt
            git_commit.txt
            run_summary.json
            full_log.jsonl
            metrics.csv
            metrics_by_turn.csv
            artifacts/
            figures/
    """

    def __init__(self, run_id: str, base_dir: str | Path = "experiments/runs") -> None:
        self.run_id = run_id
        self.run_dir = Path(base_dir) / run_id
        ensure_dir(self.run_dir)
        ensure_dir(self.run_dir / "artifacts")
        ensure_dir(self.run_dir / "figures")
        self._turn_rows: list[dict[str, Any]] = []
        self._errors: list[dict[str, Any]] = []

    # ----- Setup -----

    def write_config(self, cfg: dict[str, Any]) -> None:
        import yaml

        with (self.run_dir / "config.yaml").open("w", encoding="utf-8") as f:
            yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)

    def write_environment(self) -> None:
        lines = [
            f"run_id: {self.run_id}",
            f"timestamp: {now_iso()}",
            f"python: {platform.python_version()}",
            f"platform: {platform.platform()}",
        ]
        try:
            import sys
            pip_output = subprocess.check_output(
                [sys.executable, "-m", "pip", "list", "--format=freeze"],
                stderr=subprocess.DEVNULL,
                timeout=30,
            ).decode()
            lines.append("packages:")
            lines += [f"  {l}" for l in pip_output.strip().splitlines()]
        except Exception:
            lines.append("packages: <unavailable>")
        (self.run_dir / "environment.txt").write_text("\n".join(lines), encoding="utf-8")

    def write_git_info(self, project_dir: str | Path = ".") -> None:
        try:
            commit = subprocess.check_output(
                ["git", "rev-parse", "HEAD"],
                cwd=str(project_dir),
                stderr=subprocess.DEVNULL,
            ).decode().strip()
            status = subprocess.check_output(
                ["git", "status", "--short"],
                cwd=str(project_dir),
                stderr=subprocess.DEVNULL,
            ).decode().strip()
        except Exception:
            commit = "git_not_available"
            status = ""
        (self.run_dir / "git_commit.txt").write_text(
            f"commit: {commit}\nstatus:\n{status}", encoding="utf-8"
        )

    # ----- Mock component tracking -----

    def write_mock_warning(self, impl_modes: dict[str, str]) -> None:
        """Create MOCK_WARNING.md if any component is in mock mode.

        This file is written at run startup so it is immediately visible.
        It is intentionally eye-catching to remind that the run is NOT
        a production-quality experiment.
        """
        mock_items = {k: v for k, v in impl_modes.items() if "mock" in str(v).lower()}
        real_items = {k: v for k, v in impl_modes.items() if "mock" not in str(v).lower()}

        lines = ["# ⚠️  MOCK COMPONENTS ACTIVE — NOT A PRODUCTION RUN\n"]

        if mock_items:
            lines += [
                "This run used **rule-based / mock** replacements for the following modules.",
                "Results are for development/debugging purposes only.",
                "**These modules must be replaced before reporting paper results.**",
                "",
                "| Module | Status | What is mocked |",
                "|--------|--------|----------------|",
            ]
            mock_descriptions = {
                "llm": "LLM API not called — direction translation and hypothesis generation use rule-based templates",
                "direction_translator": "Directions described by item IDs only (no semantic LLM translation)",
                "hypothesis_generator": "Hypotheses generated by fixed rules, not LLM reasoning",
                "option_writer": "Option text templated, not polished by LLM",
                "user_simulator": "User choice is deterministic argmax (no stochastic simulation)",
                "item_encoder": "Item embeddings are random vectors (no TF-IDF/BGE encoding)",
            }
            for k, v in mock_items.items():
                desc = mock_descriptions.get(k, f"using mode: {v}")
                lines.append(f"| `{k}` | **MOCK** | {desc} |")

            lines += [
                "",
                "## What needs to change for paper results",
                "",
                "| Module | Required replacement |",
                "|--------|---------------------|",
                "| `llm` | Set `llm.mode: openai` and provide `OPENAI_API_KEY` |",
                "| `item_encoder` | Set `embedding.mode: bge` and run on GPU |",
                "| `user_simulator` | Set `simulation.user_choice_mode: stochastic_sample` |",
                "",
            ]
        else:
            lines = [
                "# ✅  All modules using real implementations",
                "",
                "No mock components detected in this run.",
                "",
                "| Module | Status |",
                "|--------|--------|",
            ]
            for k, v in real_items.items():
                lines.append(f"| `{k}` | ✅ `{v}` |")

        (self.run_dir / "MOCK_WARNING.md").write_text("\n".join(lines), encoding="utf-8")

    # ----- Per-turn logging -----

    def log_turn(self, turn_log: dict[str, Any]) -> None:
        """Append one turn record to full_log.jsonl and buffer metrics_by_turn."""
        append_jsonl([turn_log], self.run_dir / "full_log.jsonl")
        m = turn_log.get("metrics", {})
        top_k = 10
        self._turn_rows.append(
            {
                "method": turn_log.get("method", "interrec"),
                "dataset": turn_log.get("dataset", ""),
                "seed": turn_log.get("seed", 42),
                "user_id": turn_log.get("user_id", ""),
                "turn": turn_log.get("turn", 0),
                f"HitRate@{top_k}": m.get(f"HitRate@{top_k}", ""),
                f"NDCG@{top_k}": m.get(f"NDCG@{top_k}", ""),
                f"MRR@{top_k}": m.get(f"MRR@{top_k}", ""),
                "entropy": turn_log.get("belief_after", {}).get("entropy", ""),
                "preference_error": m.get("preference_error", ""),
                "ask": turn_log.get("question_selection", {}).get("ask", False),
                "IG": turn_log.get("question_selection", {}).get("IG", ""),
            }
        )

    def log_error(self, user_id: str, tb: str) -> None:
        self._errors.append({"user_id": user_id, "error": tb})
        append_jsonl([{"type": "error", "user_id": user_id, "traceback": tb}], self.run_dir / "full_log.jsonl")

    # ----- Summary / metrics flush -----

    def write_metrics(self, aggregate: dict[str, Any], all_results: list[dict[str, Any]]) -> None:
        """Write metrics.csv, metrics_by_turn.csv, and run_summary.json."""
        # metrics.csv (one row per run)
        mc_path = self.run_dir / "metrics.csv"
        with mc_path.open("w", newline="", encoding="utf-8") as f:
            if aggregate:
                writer = csv.DictWriter(f, fieldnames=list(aggregate.keys()))
                writer.writeheader()
                writer.writerow(aggregate)

        # metrics_by_turn.csv
        mbt_path = self.run_dir / "metrics_by_turn.csv"
        if self._turn_rows:
            with mbt_path.open("w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, fieldnames=list(self._turn_rows[0].keys()))
                writer.writeheader()
                writer.writerows(self._turn_rows)

        # run_summary.json
        summary = {
            "run_id": self.run_id,
            "timestamp": now_iso(),
            "n_sessions": len(all_results),
            "n_turns": len(self._turn_rows),
            "errors": len(self._errors),
            "aggregate_metrics": aggregate,
        }
        write_json(summary, self.run_dir / "run_summary.json")
